import { afterEach, describe, expect, it } from 'vitest'
import { pythonDetector } from '../src/detectors/python.js'
import { cleanup, makeProject } from './helpers.js'

const dirs: string[] = []
const project = async (files: Record<string, string>) => {
  const dir = await makeProject(files)
  dirs.push(dir)
  return dir
}
afterEach(async () => {
  await Promise.all(dirs.splice(0).map(cleanup))
})

describe('pythonDetector', () => {
  it('returns undefined without any python manifest', async () => {
    const dir = await project({ 'package.json': '{}' })
    expect(await pythonDetector.detect({ dir })).toBeUndefined()
  })

  it('reads PEP 621 metadata and defaults to pip', async () => {
    const dir = await project({
      'pyproject.toml': `
[project]
name = "my-app"
version = "3.1.4"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
`,
    })
    expect(await pythonDetector.detect({ dir })).toMatchObject({
      language: 'python',
      name: 'my-app',
      version: '3.1.4',
      versionSource: 'pyproject.toml:project.version',
      packageManager: 'pip',
      languageVersion: '>=3.11',
      manifest: 'pyproject.toml',
      lockfile: '',
    })
  })

  it('detects poetry from [tool.poetry] and reads the version from poetry.lock', async () => {
    const dir = await project({
      'pyproject.toml': `
[tool.poetry]
name = "svc"
version = "0.9.0"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
`,
      'poetry.lock': '# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.\n',
    })
    expect(await pythonDetector.detect({ dir })).toMatchObject({
      name: 'svc',
      version: '0.9.0',
      versionSource: 'pyproject.toml:tool.poetry.version',
      packageManager: 'poetry',
      packageManagerVersion: '1.8.3',
      languageVersion: '^3.10',
      lockfile: 'poetry.lock',
    })
  })

  it('detects uv from uv.lock even when the build backend is hatchling', async () => {
    const dir = await project({
      'pyproject.toml': `
[project]
name = "uvapp"
version = "1.0.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
required-version = ">=0.5"
`,
      'uv.lock': 'version = 1\n',
    })
    expect(await pythonDetector.detect({ dir })).toMatchObject({ packageManager: 'uv', packageManagerVersion: '>=0.5', lockfile: 'uv.lock' })
  })

  it('detects pdm and hatch from tool tables', async () => {
    const pdm = await project({ 'pyproject.toml': '[project]\nname="x"\nversion="1.0"\n[tool.pdm]\ndistribution = true\n' })
    expect((await pythonDetector.detect({ dir: pdm }))?.packageManager).toBe('pdm')

    const hatch = await project({ 'pyproject.toml': '[project]\nname="x"\nversion="1.0"\n[tool.hatch.envs.default]\ndependencies = []\n' })
    expect((await pythonDetector.detect({ dir: hatch }))?.packageManager).toBe('hatch')
  })

  it('detects pipenv from Pipfile and reads python version from [requires]', async () => {
    const dir = await project({
      Pipfile: '[packages]\nrequests = "*"\n\n[requires]\npython_version = "3.12"\n',
      'Pipfile.lock': '{}',
      'app/__init__.py': '__version__ = "2.2.2"\n',
    })
    expect(await pythonDetector.detect({ dir })).toMatchObject({
      packageManager: 'pipenv',
      lockfile: 'Pipfile.lock',
      manifest: 'Pipfile',
      languageVersion: '3.12',
      version: '2.2.2',
      versionSource: 'app/__init__.py',
    })
  })

  it('resolves setuptools dynamic version via attr', async () => {
    const dir = await project({
      'pyproject.toml': `
[project]
name = "dyn-pkg"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "dyn_pkg.__version__"}
`,
      'src/dyn_pkg/__init__.py': '"""Docstring."""\n__version__: str = "4.5.6"\n',
    })
    const result = await pythonDetector.detect({ dir })
    expect(result?.version).toBe('4.5.6')
    expect(result?.versionSource).toContain('tool.setuptools.dynamic')
  })

  it('resolves hatch version path', async () => {
    const dir = await project({
      'pyproject.toml': `
[project]
name = "h"
dynamic = ["version"]

[tool.hatch.version]
path = "src/h/__about__.py"
`,
      'src/h/__about__.py': "__version__ = '7.8.9'\n",
    })
    expect(await pythonDetector.detect({ dir })).toMatchObject({ version: '7.8.9', versionSource: 'src/h/__about__.py' })
  })

  it('reads setup.cfg metadata including attr: and file: directives', async () => {
    const plain = await project({ 'setup.cfg': '[metadata]\nname = cfgapp\nversion = 1.1.1\n\n[options]\npython_requires = >=3.9\n' })
    expect(await pythonDetector.detect({ dir: plain })).toMatchObject({
      name: 'cfgapp',
      version: '1.1.1',
      versionSource: 'setup.cfg:metadata.version',
      languageVersion: '>=3.9',
      manifest: 'setup.cfg',
    })

    const attr = await project({
      'setup.cfg': '[metadata]\nname = cfgapp\nversion = attr: cfgapp.__version__\n',
      'cfgapp/__init__.py': '__version__ = "2.0.0"\n',
    })
    expect((await pythonDetector.detect({ dir: attr }))?.version).toBe('2.0.0')

    const file = await project({ 'setup.cfg': '[metadata]\nname = cfgapp\nversion = file: VERSION\n', VERSION: '3.0.0\n' })
    expect((await pythonDetector.detect({ dir: file }))?.version).toBe('3.0.0')
  })

  it('reads version from setup.py', async () => {
    const dir = await project({
      'setup.py': 'from setuptools import setup\n\nsetup(\n    name="legacy",\n    version="0.1.0",\n)\n',
      'requirements.txt': 'flask\n',
    })
    expect(await pythonDetector.detect({ dir })).toMatchObject({ name: 'legacy', version: '0.1.0', versionSource: 'setup.py', packageManager: 'pip', manifest: 'setup.py' })
  })

  it('falls back to a VERSION file for a bare requirements.txt project', async () => {
    const dir = await project({ 'requirements.txt': 'django\n', VERSION: 'v5.0.0\n' })
    expect(await pythonDetector.detect({ dir })).toMatchObject({ version: '5.0.0', versionSource: 'VERSION', manifest: 'requirements.txt', packageManager: 'pip' })
  })

  it('prefers .python-version over requires-python and reads runtime.txt', async () => {
    const pinned = await project({ 'pyproject.toml': '[project]\nname="a"\nversion="1"\nrequires-python=">=3.8"\n', '.python-version': '3.12.4\n' })
    expect((await pythonDetector.detect({ dir: pinned }))?.languageVersion).toBe('3.12.4')

    const heroku = await project({ 'requirements.txt': '', 'runtime.txt': 'python-3.11.9\n' })
    expect((await pythonDetector.detect({ dir: heroku }))?.languageVersion).toBe('3.11.9')
  })

  it('leaves version empty for scm-versioned projects without git tags', async () => {
    const dir = await project({
      'pyproject.toml': '[project]\nname="scm"\ndynamic=["version"]\n[tool.setuptools_scm]\n',
    })
    const result = await pythonDetector.detect({ dir })
    expect(result?.version).toBe('')
    expect(result?.versionSource).toBe('')
  })
})
